import { ValueCard, DiagnosisQuestion } from '../types/analysis';

export const VALUE_CARDS: ValueCard[] = [
    // カテゴリーA
    { id: 1, category: 'A', name: '好奇心旺盛', isPositive: true, description: '新しい知識や体験に積極的に飛び込む。', example: '面白そうなことには即座に首を突っ込みますが、形になる前に別のことに目が行きがちです。', pairId: 2 },
    { id: 2, category: 'A', name: '飽きっぽい', isPositive: false, description: '関心が次々と移り、継続が課題。', example: '新しい知識や体験に飛び込む力が強いが、関心が次々と移るため継続が課題。', pairId: 1 },
    { id: 3, category: 'A', name: '独創的', isPositive: true, description: '誰も思いつかない斬新な発想ができる。', example: '斬新な企画を出すのは得意ですが、形式的な手続きやマナーを疎かにして怒られることがあります。', pairId: 4 },
    { id: 4, category: 'A', name: '常識軽視', isPositive: false, description: '既存のルールやマナーを軽視しがち。', example: '誰も思いつかない発想ができるが、既存のルールやマナーを「つまらない」と無視する傾向。', pairId: 3 },
    { id: 5, category: 'A', name: '論理的', isPositive: true, description: '客観的なデータや理屈に基づき判断する。', example: '全ての行動の根拠を説明できますが、周囲からは「冷たい」「理屈ばかり」と言われることも。', pairId: 6 },
    { id: 6, category: 'A', name: '理屈っぽい', isPositive: false, description: '感情や直感を切り捨て、理詰めで考えすぎる。', example: 'データに基づき冷静に判断できるが、理屈で説明できない感情や直感を切り捨てがち。', pairId: 5 },
    { id: 7, category: 'A', name: '審美眼', isPositive: true, description: '質の高いものを見抜く力がある。', example: 'デザインの細部までこだわり抜けますが、納得がいかないと納期ギリギリまで修正を止められません。', pairId: 8 },
    { id: 8, category: 'A', name: '妥協できない', isPositive: false, description: '自分の美意識に合わないものを極端に嫌う。', example: '質の高いものを見抜く力があるが、自分の美意識に合わないものを極端に嫌う。', pairId: 7 },
    { id: 9, category: 'A', name: '探究心', isPositive: true, description: '一つのことを深く掘り下げる専門性を持つ。', example: '技術的な課題の追求には時間を忘れますが、本来の目的とは違う細部で立ち止まってしまいます。', pairId: 10 },
    { id: 10, category: 'A', name: '細部にこだわる', isPositive: false, description: '枝葉末節に囚われて全体が遅れる。', example: '一つのことを深く掘り下げる専門性を持つが、枝葉末節に囚われて全体が遅れる。', pairId: 9 },
    { id: 11, category: 'A', name: '大局観', isPositive: true, description: '未来の展開を予測し戦略を立てられる。', example: '3年後のビジョンを描くのは得意ですが、目の前の経費精算や日報はつい後回しにします。', pairId: 12 },
    { id: 12, category: 'A', name: '実務軽視', isPositive: false, description: '日々の地道な作業や事務処理を軽視する。', example: '未来の展開を予測し戦略を立てられるが、日々の地道な作業や事務処理を軽視する。', pairId: 11 },
    { id: 13, category: 'A', name: '柔軟な視点', isPositive: true, description: '多様な視点から物事を見られる。', example: '人の意見を聞いて良い点を取り入れるのは得意ですが、「結局どうしたいの？」と言われることも。', pairId: 14 },
    { id: 14, category: 'A', name: 'ブレやすい', isPositive: false, description: '周囲の影響を受けやすく方針がブレやすい。', example: '多様な視点から物事を見られるが、周囲の影響を受けやすく方針がブレやすい。', pairId: 13 },
    { id: 15, category: 'A', name: '批判的思考', isPositive: true, description: '問題点を見抜く力が高い。', example: '計画の穴を即座に指摘できますが、言い方がきつくて相手を萎縮させてしまうことが悩みです。', pairId: 16 },
    { id: 16, category: 'A', name: '否定的', isPositive: false, description: '改善案より先にダメ出しが出る。', example: '問題点を見抜く力が高いが、改善案より先にダメ出しが出るため周囲の士気を下げがち。', pairId: 15 },
    { id: 17, category: 'A', name: '理想', isPositive: true, description: '高い志で人を鼓舞できる。', example: '「世界を変えよう」と本気で思っていますが、具体的な資金繰りや人員計画の話になると弱いです。', pairId: 18 },
    { id: 18, category: 'A', name: '空想癖', isPositive: false, description: '実現可能性を無視した話になりやすい。', example: '高い志で人を鼓舞できるが、実現可能性を無視した極端な話になりやすい。', pairId: 17 },
    { id: 19, category: 'A', name: '抽象概念', isPositive: true, description: '複雑な仕組みや概念を掴むのが早い。', example: '哲学的な話やビジネスモデルの根幹は理解できますが、現場への指示が「いい感じに」と曖昧になりがち。', pairId: 20 },
    { id: 20, category: 'A', name: '具体性欠如', isPositive: false, description: '具体的な指示が出せない。', example: '複雑な仕組みや概念を掴むのが早いが、説明が抽象的で具体的な指示が出せない。', pairId: 19 },

    // カテゴリーB
    { id: 21, category: 'B', name: '積極的', isPositive: true, description: '自ら動いて道を切り拓く。', example: '課題を見つけたら即行動します。ただ、後で「実は事情があった」と聞かされることもしばしば。', pairId: 22 },
    { id: 22, category: 'B', name: '話を聞かない', isPositive: false, description: '周囲の状況を確認する前に動いてしまう。', example: '自ら動いて道を切り拓くが、周囲の状況やアドバイスを確認する前に動いてしまう。', pairId: 21 },
    { id: 23, category: 'B', name: 'リーダーシップ', isPositive: true, description: '集団をまとめ前進させる推進力がある。', example: '困難な場面でもチームを引っ張りますが、後で「もっと相談してほしかった」と不満が出ることも。', pairId: 24 },
    { id: 24, category: 'B', name: '強引', isPositive: false, description: '反対意見を押し切ってしまう傾向がある。', example: '集団をまとめ前進させる推進力があるが、反対意見を押し切ってしまう傾向がある。', pairId: 23 },
    { id: 25, category: 'B', name: '楽天家', isPositive: true, description: 'どんな逆境も明るく乗り越える。', example: '失敗しても「次がある！」と切り替えられますが、同じミスを繰り返してしまうことがあります。', pairId: 26 },
    { id: 26, category: 'B', name: '危機感不足', isPositive: false, description: '楽観視しすぎて事前の備えを怠る。', example: 'どんな逆境も明るく乗り越えるが、楽観視しすぎて事前の備えを怠りやすい。', pairId: 25 },
    { id: 27, category: 'B', name: '情熱的', isPositive: true, description: '強い使命感でコミットする。', example: '仕事には全力投球です。でも、定時で帰りたいメンバーとの温度差に悩むことがあります。', pairId: 28 },
    { id: 28, category: 'B', name: '温度差を生む', isPositive: false, description: '自分と同じ熱量を他人に強要しがち。', example: '強い使命感でコミットするが、自分と同じ熱量を他人に強要し、周囲を疲れさせる。', pairId: 27 },
    { id: 29, category: 'B', name: '社交的', isPositive: true, description: '誰とでもすぐ打ち解ける。', example: '交流会やパーティは大得意です。でも、休日に一人でじっとしていると何をすればいいか分かりません。', pairId: 30 },
    { id: 30, category: 'B', name: '内省不足', isPositive: false, description: '常に外の刺激を求め、自分と向き合う時間が不足。', example: '誰とでもすぐ打ち解けるが、常に外の刺激を求めてしまい、自分と向き合う時間が不足。', pairId: 29 },
    { id: 31, category: 'B', name: '決断力', isPositive: true, description: '迷わず決めることで停滞を防ぐ。', example: 'その場でパッと判断できるのが強みですが、後から「もっと調べておけばよかった」と思うこと多々。', pairId: 32 },
    { id: 32, category: 'B', name: '思慮が浅い', isPositive: false, description: '重要な考慮事項を見落としたまま決定しがち。', example: '迷わず決めることで停滞を防ぐが、重要な考慮事項を見落としたまま決定してしまう。', pairId: 31 },
    { id: 33, category: 'B', name: 'フットワーク', isPositive: true, description: 'どこへでも飛んでいき人脈を広げる。', example: '新しい案件の立ち上げにはどこへでも行きますが、維持・管理フェーズになると飽きてしまいます。', pairId: 34 },
    { id: 34, category: 'B', name: '定着が苦手', isPositive: false, description: '一つの場所に長く留まって深掘りするのが苦痛。', example: 'どこへでも飛んでいき人脈を広げるが、一つの場所に長く留まって深掘りするのが苦痛。', pairId: 33 },
    { id: 35, category: 'B', name: '負けず嫌い', isPositive: true, description: '高い目標を追い続けるバイタリティ。', example: 'ライバルがいるほど燃えますが、他人が成功しているのを見ると焦りや嫉妬を感じて苦しいです。', pairId: 36 },
    { id: 36, category: 'B', name: '比較疲弊', isPositive: false, description: '常に他人の目を気にして心が休まらない。', example: '高い目標を追い続けるバイタリティがあるが、常に他人の目を気にして心が休まらない。', pairId: 35 },
    { id: 37, category: 'B', name: 'スピード重視', isPositive: true, description: '圧倒的な速さでアウトプットする。', example: '資料作成は誰よりも早いです。ただ、誤字脱字や計算ミスを指摘されることがよくあります。', pairId: 38 },
    { id: 38, category: 'B', name: '詰めが甘い', isPositive: false, description: '確認不足による単純ミスを出しやすい。', example: '圧倒的な速さでアウトプットするが、確認不足による単純ミスを出しやすい。', pairId: 37 },
    { id: 39, category: 'B', name: '巻き込み力', isPositive: true, description: '周囲をその気にさせて動かすのが上手い。', example: '困っている人を見ると放っておけず協力しますが、「余計なことをしないで」と言われることも。', pairId: 40 },
    { id: 40, category: 'B', name: '干渉しすぎ', isPositive: false, description: '相手の領域に踏み込みすぎて嫌がられる。', example: '周囲をその気にさせて動かすのが上手いが、相手の領域に踏み込みすぎて嫌がられる。', pairId: 39 },

    // カテゴリーC
    { id: 41, category: 'C', name: '計画的', isPositive: true, description: '完璧なスケジュールを立てて実行する。', example: '準備万端で挑むのが得意です。でも、当日急な変更が入ると、どう立て直せばいいか動揺します。', pairId: 42 },
    { id: 42, category: 'C', name: '変化に弱い', isPositive: false, description: '予期せぬトラブルが起きるとパニックになる。', example: '完璧なスケジュールを立てて実行するが、予期せぬトラブルが起きるとパニックになる。', pairId: 41 },
    { id: 43, category: 'C', name: '責任感', isPositive: true, description: '任されたことを絶対にやり遂げる。', example: '締め切りは死守します。でも、夜通し一人で作業して体調を崩してしまうこともあります。', pairId: 44 },
    { id: 44, category: 'C', name: '抱え込みすぎる', isPositive: false, description: '他人に頼ることを「逃げ」と感じてしまう。', example: '任されたことを絶対にやり遂げるが、他人に頼ることを「逃げ」と感じて限界まで抱え込む。', pairId: 43 },
    { id: 45, category: 'C', name: '几帳面', isPositive: true, description: 'ミスのない高品質な仕事をする。', example: '細かいチェックは欠かしません。ただ、一つの資料にこだわりすぎて全体が遅れることがあります。', pairId: 46 },
    { id: 46, category: 'C', name: '完璧主義', isPositive: false, description: '100点を目指しすぎて期限に間に合わない。', example: 'ミスのない高品質な仕事をするが、100点を目指しすぎて期限に間に合わなくなるリスク。', pairId: 45 },
    { id: 47, category: 'C', name: '持続力', isPositive: true, description: '困難でも諦めずに解決を目指す。', example: '一度始めたことは最後までやります。でも、明らかに効率が悪い方法でも変えるのをためらいます。', pairId: 48 },
    { id: 48, category: 'C', name: '固執・しつこい', isPositive: false, description: '見込みのないアイデアや手法にも固執しがち。', example: '困難でも諦めずに解決を目指すが、見込みのないアイデアや手法にも固執してしまう。', pairId: 47 },
    { id: 49, category: 'C', name: '自制心', isPositive: true, description: '自分を律して高い成果を出す。', example: '自分に妥協は許しません。でも、他人が少しミスをしただけで「やる気があるのか」と詰めてしまいがち。', pairId: 50 },
    { id: 50, category: 'C', name: '他人に厳しい', isPositive: false, description: '周囲の「甘さ」や「ゆとり」が許せない。', example: '自分を律して高い成果を出すが、周囲の「甘さ」や「ゆとり」が許せず攻撃的になる。', pairId: 49 },
    { id: 51, category: 'C', name: '規律重視', isPositive: true, description: '組織のルールを忠実に守る。', example: '正しくルールを運用するのは得意です。でも、「今回だけは特例で」という依頼は絶対断ります。', pairId: 52 },
    { id: 52, category: 'C', name: '融通が利かない', isPositive: false, description: '事に応じた臨機応変な対応を拒む。', example: '組織のルールを忠実に守るが、状況に応じた臨機応変な対応を「不正」と感じて拒む。', pairId: 51 },
    { id: 53, category: 'C', name: '緻密', isPositive: true, description: '正確な作業をする能力に長ける。', example: '表計算の数式一つひとつは完璧に作れますが、「そもそも何のための分析か」を忘れることが……。', pairId: 54 },
    { id: 54, category: 'C', name: '視点が狭い', isPositive: false, description: '全体像を見失いやすい。', example: '木を見る能力に長け、正確な作業をするが、森（全体の目的）を忘れて迷走する。', pairId: 53 },
    { id: 55, category: 'C', name: '正直・誠実', isPositive: true, description: '嘘をつけず、信頼を重んじる。', example: '隠し事はしません。でも、上司に対しても「その考えは時代遅れです」とストレートに言ってしまいます。', pairId: 56 },
    { id: 56, category: 'C', name: '配慮欠如', isPositive: false, description: '正直すぎて人を傷つけることがある。', example: '嘘をつけず、信頼を重んじるが、言わなくてもいい真実を口にして対人トラブルを招く。', pairId: 55 },
    { id: 57, category: 'C', name: '安定志向', isPositive: true, description: '安心感のある確実な成果を出す。', example: '慣れた仕事は高い質でこなせます。でも、新しいシステムへの移行期は仕事が手につかなくなります。', pairId: 58 },
    { id: 58, category: 'C', name: '挑戦回避', isPositive: false, description: '新しいツールや環境への移行に不安。', example: '安心感のある確実な成果を出すが、新しいツールや環境への移行に強い不安を感じて拒絶する。', pairId: 57 },
    { id: 59, category: 'C', name: '伝統重視', isPositive: true, description: '守るべき価値観を大切にする。', example: '古き良き企業の伝統を守りたいです。ただ、SNSを活用した広報などは必要ないと感じてしまいます。', pairId: 60 },
    { id: 60, category: 'C', name: '排他的', isPositive: false, description: '新しい流行や価値観を軽薄だと決めつけがち。', example: '守るべき価値観を大切にするが、新しい流行や価値観を「軽薄」だと決め付ける傾向。', pairId: 59 },

    // カテゴリーD
    { id: 61, category: 'D', name: '共感力', isPositive: true, description: '相手の痛みを自分事として捉えられる。', example: '悩んでいる人の気持ちに深く寄り添えますが、その後自分まで落ち込んで動けなくなってしまいます。', pairId: 62 },
    { id: 62, category: 'D', name: '情に流される', isPositive: false, description: '負の感情も吸収してしまい疲弊する。', example: '相手の痛みを自分事として捉えられるが、負の感情も吸収してしまい精神的に疲弊する。', pairId: 61 },
    { id: 63, category: 'D', name: '親しみやすさ', isPositive: true, description: '誰からも好かれ職場を和ませる。', example: 'チームの雰囲気作りは得意です。でも、親しすぎて部下のミスを厳しく指摘できず、なぁなぁに。', pairId: 64 },
    { id: 64, category: 'D', name: 'けじめが甘い', isPositive: false, description: '仲良くなりすぎて厳しい指示ができない。', example: '誰からも好かれ職場を和ませるが、仲良くなりすぎて厳しい指示や注意ができなくなる。', pairId: 63 },
    { id: 65, category: 'D', name: '献身的', isPositive: true, description: '他者のために尽くすことに喜びを感じる。', example: '頼まれると断れず自分を後回しにします。気づくと自分自身の課題が全く進んでいないことがよくあります。', pairId: 66 },
    { id: 66, category: 'D', name: '自己犠牲', isPositive: false, description: '自分のキャパシティを無視して働きすぎる。', example: '他者のために尽くすことに喜びを感じるが、自分のキャパシティを無視して働きすぎる。', pairId: 65 },
    { id: 67, category: 'D', name: '寛容', isPositive: true, description: '少々のミスや遅配を許せる包容力。', example: '部下の遅刻も「事情があるんだろう」と許せますが、それが習慣化してチームの規律が乱れがちに。', pairId: 68 },
    { id: 68, category: 'D', name: 'ルーズ', isPositive: false, description: '組織としての締まりを緩めてしまう。', example: '少々のミスや遅配を許せる包容力があるが、組織としての締まりを緩めてしまう。', pairId: 67 },
    { id: 69, category: 'D', name: '謙虚', isPositive: true, description: '学ぶ姿勢が強く周囲を敬う。', example: 'アドバイスは何でも吸収します。でも、本当は自分の考えがあっても「自信がないので」と黙ってしまいます。', pairId: 70 },
    { id: 70, category: 'D', name: '自信なし', isPositive: false, description: '自分を過小評価して建設的な主張を控える。', example: '学ぶ姿勢が強く周囲を敬うが、自分を過小評価して建設的な主張も控えてしまう。', pairId: 69 },
    { id: 71, category: 'D', name: 'チーム重視', isPositive: true, description: '協力体制を築き大きな成果を出す。', example: 'みんなで協力するのは楽しいです。でも、企画を丸投げされると誰に相談すればいいか迷って固まります。', pairId: 72 },
    { id: 72, category: 'D', name: '依存', isPositive: false, description: '裁量が大きい仕事を任されると不安で止まる。', example: '協力体制を築き大きな成果を出すが、一人の裁量が大きい仕事を任されると不安で足が止まる。', pairId: 71 },
    { id: 73, category: 'D', name: 'ホスピタリティ', isPositive: true, description: '相手の期待に応える努力を惜しまない。', example: '全員の希望を聞いて調整しようとしますが、結局中途半端な案になり、各方面からお叱りを受ける結果に。', pairId: 74 },
    { id: 74, category: 'D', name: '八方美人', isPositive: false, description: '対立を恐れて結局誰も満足させられない。', example: '顧客や他者の期待に応える努力を惜しまないが、対立を恐れて板挟みになり、結局誰も満足させられない。', pairId: 73 },
    { id: 75, category: 'D', name: '調整役', isPositive: true, description: '対立する意見の落とし所を見つける。', example: '険悪な会議の場を収めるのは得意ですが、「結局何も決まっていない」という批判を受けることがあります。', pairId: 76 },
    { id: 76, category: 'D', name: '事なかれ主義', isPositive: false, description: '根本解決を避けて現状維持を好む。', example: '対立する意見の間に入って落とし所を見つけるが、根本解決を避けて現状維持を好む。', pairId: 75 },
    { id: 77, category: 'D', name: '社会貢献', isPositive: true, description: '社会全体の利益のために活動できる。', example: 'ボランティア活動には熱心ですが、そのせいで家庭の時間や本来の業務時間を削ってしまうことがあります。', pairId: 78 },
    { id: 78, category: 'D', name: '足元疎か', isPositive: false, description: '目の前の家族や同僚を疎かにしがち。', example: '社会全体の利益のために活動できるが、遠くの理想を優先して目の前の家族や同僚を疎かにする。', pairId: 77 },
    { id: 79, category: 'D', name: '郷土愛', isPositive: true, description: '地域のために献身的に動ける。', example: '地元の伝統を守り抜く自信はあります。でも、都会から来たコンサルの提案にはつい反発してしまいます。', pairId: 80 },
    { id: 80, category: 'D', name: '閉鎖的', isPositive: false, description: '新しい考え方に警戒心を抱き排数的。', example: '地域のために献身的に動けるが、外から来た人や新しい考え方に警戒心を抱き、排他的になる。', pairId: 79 },

    // カテゴリーE
    { id: 81, category: 'E', name: '泰然自若', isPositive: true, description: 'どんな状況でも動じず冷静。', example: '淡々と仕事をこなすのが得意です。でも、成功しても無表情なので「嬉しくないの？」と聞かれます。', pairId: 82 },
    { id: 82, category: 'E', name: '反応が薄い', isPositive: false, description: '「やる気がない」と誤解されることも。', example: 'どんな状況でも動じず冷静だが、他者からは「やる気がない」「喜んでいない」と誤解される。', pairId: 81 },
    { id: 83, category: 'E', name: '精神的自立', isPositive: true, description: '自分の軸を持って独立独歩で進める。', example: '一人で集中して完成させる方が楽です。困っても「迷惑をかけたくない」と思ってギリギリまで黙っています。', pairId: 84 },
    { id: 84, category: 'E', name: '孤立', isPositive: false, description: 'チームプレイを拒み、孤立しやすい。', example: '自分の軸を持って独立独歩で進めるが、チームプレイを拒み、孤立しやすい。', pairId: 83 },
    { id: 85, category: 'E', name: 'ストレス耐性', isPositive: true, description: 'プレッシャーのかかる環境でも平気。', example: '過酷な状況でもメンタルが折れません。でも、部下が精神的に限界なのに気づかず「あと少し！」と励ましてしまう。', pairId: 86 },
    { id: 86, category: 'E', name: '鈍感', isPositive: false, description: 'メンバーの疲弊サインを見落としがち。', example: 'プレッシャーのかかる環境でも平気だが、精神的に疲弊しているメンバーのサインを見逃しやすい。', pairId: 85 },
    { id: 87, category: 'E', name: '冷静沈着', isPositive: true, description: '感情をコントロールし的確な指示を出す。', example: 'トラブル時もパニックになりません。でも、泣いている人に「泣いても解決しないよ」と言って火に油を注いだことが……。', pairId: 88 },
    { id: 88, category: 'E', name: '冷淡', isPositive: false, description: '相手への配慮や共感が欠けて見える。', example: '感情をコントロールし적確な指示を出すが、相手への配慮や共感が欠けているように見える。', pairId: 87 },
    { id: 89, category: 'E', name: '慎重', isPositive: true, description: '石橋を叩いて渡る慎重さで失敗を防ぐ。', example: '最悪の事態を想定して動きます。ただ、「今はGoだ！」という局面でも懸念点ばかり探して乗り遅れます。', pairId: 90 },
    { id: 90, category: 'E', name: '消極的', isPositive: false, description: '決断に時間がかかりチャンスを逃す。', example: '石橋を叩いて渡る慎重さで失敗を防ぐが、決断に時間がかかりすぎてビジネスチャンスを失う。', pairId: 89 },
    { id: 91, category: 'E', name: '内省', isPositive: true, description: '自分の行動を振り返り学習効果を得る。', example: '一日の終わりに必ず振り返りをします。でも、失敗の原因を考えすぎて、翌日起きるのが辛いこともあります。', pairId: 92 },
    { id: 92, category: 'E', name: '考えすぎ', isPositive: false, description: '過去の失敗や未来の不安に囚われやすい。', example: '自分の行動を振り返り、高い学習効果を得るが、過去の失敗や未来の不安に囚われやすい。', pairId: 91 },
    { id: 93, category: 'E', name: '裏表がない', isPositive: true, description: '言動が一致しており信頼される。', example: '思ったことをそのまま口にする正直さがあります。ただ、その場の空気を凍らせるような暴露をしてしまうことも……。', pairId: 94 },
    { id: 94, category: 'E', name: '無遠慮', isPositive: false, description: '配慮に欠け不用意な暴露をしてしまう。', example: '言動が一致しており信頼されるが、言ってはいけない隠し事やデリケートな話題も不用意に漏らす。', pairId: 93 },
    { id: 95, category: 'E', name: '冷静沈着(安定)', isPositive: true, description: 'ゆったりと構えて周囲に安心感を与える。', example: '何が起きてもマイペースでいられます。でも、納期間際で部下が焦っていても「なんとかなるよ」とどこ吹く風。', pairId: 96 },
    { id: 96, category: 'E', name: '危機感なし', isPositive: false, description: '緊急事態でもペースを崩せない。', example: 'ゆったりと構えて周囲に安心感を与えるが、緊急事態でもペースを崩せず周囲をイライラさせる。', pairId: 95 },
    { id: 97, category: 'E', name: '向上心', isPositive: true, description: '常に高い場所を目指して努力を続ける。', example: '次々と目標をクリアしていきたいです。でも、達成した瞬間にはもう次の不安があって、心が満たされません。', pairId: 98 },
    { id: 98, category: 'E', name: '幸福感欠如', isPositive: false, description: '今の幸せや達成感に目を向ける余裕がない。', example: '常に高い場所を目指して努力を続けるが、今の幸せや達成感に目を向ける余裕がない。', pairId: 97 },
    { id: 99, category: 'E', name: '平和主義', isPositive: true, description: '争いを避け、穏やかな関係を築く。', example: '誰とも喧嘩したくないです。だから、納得のいかない指示でも、空気を壊さないように黙って従います。', pairId: 100 },
    { id: 100, category: 'E', name: '主張できない', isPositive: false, description: '改善に必要な健全な衝突すら嫌い放置。', example: '争いを避け、穏やかな関係を築く力があるが、改善に必要な健全な衝突すら嫌い、問題を放置。', pairId: 99 },
];

export const DIAGNOSIS_QUESTIONS: DiagnosisQuestion[] = [
    { id: 1, category: 'A', text: '新しい知識や、体験したことのない分野に飛び込むのが好きだ。', positiveValueId: 1, negativeValueId: 2 },
    { id: 2, category: 'A', text: '既存のやり方に捉われず、自分なりの新しいアイデアを生み出したい。', positiveValueId: 3, negativeValueId: 4 },
    { id: 3, category: 'A', text: '感情よりも、客観的なデータや理屈に基づいて物事を判断する方だ。', positiveValueId: 5, negativeValueId: 6 },
    { id: 4, category: 'A', text: '物事の美しさやデザイン、質の高さにはこだわりたい。', positiveValueId: 7, negativeValueId: 8 },
    { id: 5, category: 'A', text: '一つのことを徹底的に調べたり、深く掘り下げたりすることが苦ではない。', positiveValueId: 9, negativeValueId: 10 },
    { id: 6, category: 'A', text: '目の前の作業よりも、将来の展望や全体の戦略を考える方が得意だ。', positiveValueId: 11, negativeValueId: 12 },
    { id: 7, category: 'A', text: '状況に応じて、自分の考えや手法を柔軟に変えることができる。', positiveValueId: 13, negativeValueId: 14 },
    { id: 8, category: 'A', text: '物事の問題点や、隠れた矛盾に気づき、率直に指摘できる。', positiveValueId: 15, negativeValueId: 16 },
    { id: 9, category: 'A', text: '現実の制約を一旦置いて、「理想の世界」を想像することがよくある。', positiveValueId: 17, negativeValueId: 18 },
    { id: 10, category: 'A', text: '抽象的な概念や、複雑な理論の話を理解するのが早い方だ。', positiveValueId: 19, negativeValueId: 20 },
    { id: 11, category: 'B', text: '迷うくらいなら、まずは結果を恐れずに行動を開始する。', positiveValueId: 21, negativeValueId: 22 },
    { id: 12, category: 'B', text: 'チームの中で、自分が旗振り役となって周囲を引っ張りたい。', positiveValueId: 23, negativeValueId: 24 },
    { id: 13, category: 'B', text: 'どんな状況でも「何とかなるだろう」という前向きな確信がある。', positiveValueId: 25, negativeValueId: 26 },
    { id: 14, category: 'B', text: '何かに取り組む時は、周囲が圧倒されるほどの熱量で打ち込みたい。', positiveValueId: 27, negativeValueId: 28 },
    { id: 15, category: 'B', text: '初対面の人や、様々な集まりに参加して人脈を広げるのは楽しい。', positiveValueId: 29, negativeValueId: 30 },
    { id: 16, category: 'B', text: '多くの選択肢があっても、その場で素早く「これだ」と決められる。', positiveValueId: 31, negativeValueId: 32 },
    { id: 17, category: 'B', text: '興味がある場所には、どこへでもすぐに出かけていく方だ。', positiveValueId: 33, negativeValueId: 34 },
    { id: 18, category: 'B', text: '他人と競い合ったり、高い目標を目指して自分を高めるのが好きだ。', positiveValueId: 35, negativeValueId: 36 },
    { id: 19, category: 'B', text: '仕事の質を極めることよりも、まずは圧倒的なスピードを出したい。', positiveValueId: 37, negativeValueId: 38 },
    { id: 20, category: 'B', text: '周囲の人のやる気に火をつけ、行動を促すことが得意だ。', positiveValueId: 39, negativeValueId: 40 },
    { id: 21, category: 'C', text: '実行に移す前に、綿密な計画や段取りを組むことを欠かさない。', positiveValueId: 41, negativeValueId: 42 },
    { id: 22, category: 'C', text: '一度引き受けた役割は、どんなに苦しくても最後までやり抜く。', positiveValueId: 43, negativeValueId: 44 },
    { id: 23, category: 'C', text: '小さなミスも見逃さず、丁寧に、正確に仕事を完遂したい。', positiveValueId: 45, negativeValueId: 46 },
    { id: 24, category: 'C', text: 'なかなか結果が出なくても、諦めずに地道な努力を続けられる。', positiveValueId: 47, negativeValueId: 48 },
    { id: 25, category: 'C', text: '誘惑に負けず、自分を厳しく律してストイックに振る舞う方だ。', positiveValueId: 49, negativeValueId: 50 },
    { id: 26, category: 'C', text: '決められたルールや手順、慣習を守ることを大切にしている。', positiveValueId: 51, negativeValueId: 52 },
    { id: 27, category: 'C', text: '数値管理や書類の整理など、緻密さが求められる作業が得意だ。', positiveValueId: 53, negativeValueId: 54 },
    { id: 28, category: 'C', text: '相手が誰であっても、自分を飾らずに正直に意見を言う方だ。', positiveValueId: 55, negativeValueId: 56 },
    { id: 29, category: 'C', text: '大きな変化を求めるよりも、今の安定した仕組みを改善していきたい。', positiveValueId: 57, negativeValueId: 58 },
    { id: 30, category: 'C', text: '自分が所属する組織や地域の伝統、歴史を重んじたい。', positiveValueId: 59, negativeValueId: 60 },
    { id: 31, category: 'D', text: '相手の話を聞いていると、自分のことのようにその感情を感じ取れる。', positiveValueId: 61, negativeValueId: 62 },
    { id: 32, category: 'D', text: '誰とでも打ち解けやすく、場を和ませる雰囲気が自分にあると思う。', positiveValueId: 63, negativeValueId: 64 },
    { id: 33, category: 'D', text: '自分の成果よりも、他人の成長や成功をサポートすることに喜びを感じる。', positiveValueId: 65, negativeValueId: 66 },
    { id: 34, category: 'D', text: '他人の欠点や失敗に対しても、「仕方ない」と笑って許せる方だ。', positiveValueId: 67, negativeValueId: 68 },
    { id: 35, category: 'D', text: '常に周囲から学び、自分の実力を鼻にかけない姿勢を心がけている。', positiveValueId: 69, negativeValueId: 70 },
    { id: 36, category: 'D', text: '一人で判断して進めるより、チームで話し合って決める方が安心する。', positiveValueId: 71, negativeValueId: 72 },
    { id: 37, category: 'D', text: 'サービス精神が旺盛で、相手が何を求めているかを常に考えている。', positiveValueId: 73, negativeValueId: 74 },
    { id: 38, category: 'D', text: '意見が対立している場面でも、双方が納得できる中間点を探せる。', positiveValueId: 75, negativeValueId: 76 },
    { id: 39, category: 'D', text: '日々の業務とは別に、社会全体のためになる活動に関心が高い。', positiveValueId: 77, negativeValueId: 78 },
    { id: 40, category: 'D', text: '地元のイベントや地域活動には、進んで協力・参加したい。', positiveValueId: 79, negativeValueId: 80 },
    { id: 41, category: 'E', text: '緊急事態でも、表情や態度を変えずに落ち着いて対処できる。', positiveValueId: 81, negativeValueId: 82 },
    { id: 42, category: 'E', text: '他人に相談せずとも、自分なりの考えと責任で行動を決定できる。', positiveValueId: 83, negativeValueId: 84 },
    { id: 43, category: 'E', text: '厳しい批判や大きなプレッシャーを受けても、あまり動じない。', positiveValueId: 85, negativeValueId: 86 },
    { id: 44, category: 'E', text: 'トラブルがあった時でも、感情的にならず冷静な分析に回れる。', positiveValueId: 87, negativeValueId: 88 },
    { id: 45, category: 'E', text: '失敗を最小限にするため、石橋を叩いて渡るような慎重さを持っている。', positiveValueId: 89, negativeValueId: 90 },
    { id: 46, category: 'E', text: '自分の言動が正しかったか、静かな場所で深く振り返る時間が大切だ。', positiveValueId: 91, negativeValueId: 92 },
    { id: 47, category: 'E', text: '心で思っていることと、実際に口に出す言葉にはほとんど差がない。', positiveValueId: 93, negativeValueId: 94 },
    { id: 48, category: 'E', text: '物事が計画通りに進まなくても、ゆったりと構えていられる。', positiveValueId: 95, negativeValueId: 96 },
    { id: 49, category: 'E', text: '今の成果に満足せず、常に「さらなる高み」を目指し続けたい。', positiveValueId: 97, negativeValueId: 98 },
    { id: 50, category: 'E', text: '周囲との対立や争いごとは、できる限り未然に避けたい。', positiveValueId: 99, negativeValueId: 100 },
];
