import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function GET(req: Request) {
    const { searchParams } = new URL(req.url);
    const isDebug = searchParams.get('debug') === 'true';

    if (isDebug) {
        const geminiKeys = Object.keys(process.env).filter(k => k.toLowerCase().includes('gemini'));
        const key = process.env.GEMINI_API_KEY || process.env[geminiKeys[0]];
        return NextResponse.json({
            status: 'debug_mode',
            hasKey: !!key,
            foundGeminiKeys: geminiKeys,
            keyLength: key ? (key as string).length : 0,
            maskedKey: key ? `${(key as string).substring(0, 4)}...${(key as string).substring((key as string).length - 4)}` : 'none',
            nextRuntime: (globalThis as any).process?.env?.NEXT_RUNTIME || 'unknown',
            envKeysCount: Object.keys(process.env).length,
            matchingKeys: Object.keys(process.env).filter(k => k.includes('GEMINI') || k.includes('API') || k.includes('KEY')),
            timestamp: new Date().toISOString()
        });
    }

    return NextResponse.json({ message: 'AI Analysis Endpoint' });
}

const MODEL_NAME = 'gemini-2.0-flash-001';

export async function POST(req: Request) {
    try {
        // Gemini API Key from Vercel Environment Variables
        // Note: Adding a key in Vercel UI requires a NEW DEPLOYMENT to take effect.
        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            console.error('[AI Analysis] GEMINI_API_KEY is not defined in process.env');
            return NextResponse.json({
                error: 'API Key not configured',
                tip: 'Vercelの環境設定でGEMINI_API_KEYを追加した後、Redeployを必ず実行してください。'
            }, { status: 500 });
        }

        const body = await req.json().catch(() => null);
        if (!body) {
            return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
        }

        const { messages, specialists, articles, posts } = body;
        const latestMessage = messages?.[messages.length - 1]?.text || '';

        // Limit context size to avoid token overflow
        const slicedSpecs = specialists?.slice(0, 10) || [];
        const slicedArticles = articles?.slice(0, 5) || [];
        const slicedPosts = posts?.slice(0, 5) || [];

        const prompt = `
        あなたは愛媛県のママを支援するプラットフォーム「Baby Base」のAI案内コンシェルジュです。
        ユーザー（ママ）からの育児相談に対し、温かく共感を持って答え、最適な専門家や情報を提案してください。

        【提供可能なリソース】
        ■ 専門家（Specialists）:
        ${JSON.stringify(slicedSpecs.map((s: any) => ({ id: s.id, name: s.name, category: s.category, description: s.description, tags: s.tags })))}

        ■ 記事・eラーニング（Articles）:
        ${JSON.stringify(slicedArticles.map((a: any) => ({ id: a.id, title: a.title, category: a.category })))}

        ■ 投稿・SNS（Posts）:
        ${JSON.stringify(slicedPosts.map((p: any) => ({ id: p.id, content: p.content })))}

        【ユーザーの相談内容】
        "${latestMessage}"

        【出力指示】
        1. ユーザーの悩みに対し、100〜150文字程度で、まず寄り添い、温かいアドバイスを返答してください。
        2. 上記リストの中から、相談内容に深く関連するものを最大3つまで選んでください。
        3. 出力は必ず以下のJSON形式のみ（Markdown含まず）にしてください。

        {
            "responseText": "AIからの共感メッセージ",
            "recommendations": [
                { "type": "specialist" | "article" | "post", "id": "リソースのID" }
            ]
        }
        `;

        console.log('[AI Analysis] Fetching Gemini API...');
        const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${apiKey}`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                contents: [{ parts: [{ text: prompt }] }]
            })
        });

        const data = await response.json().catch(() => ({ error: { message: 'Failed to parse Gemini response as JSON' } }));

        if (!response.ok) {
            console.error('[AI Analysis] Gemini API Error Response:', data);
            return NextResponse.json({
                error: data.error?.message || 'Gemini API Error',
                details: data.error || 'No details'
            }, { status: response.status });
        }

        const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!textResult) {
            console.error('[AI Analysis] No content generated', data);
            throw new Error('No content generated by AI');
        }

        // Robust JSON cleaning
        const jsonStr = textResult.replace(/```json\n?|\n?```/g, '').trim();
        try {
            const analysis = JSON.parse(jsonStr);
            console.log('[AI Analysis] Success:', analysis.responseText.substring(0, 20));
            return NextResponse.json(analysis);
        } catch (parseError) {
            console.error('[AI Analysis] JSON Parse Error:', parseError, 'Raw Text:', textResult);
            return NextResponse.json({ error: 'Failed to parse AI response' }, { status: 500 });
        }

    } catch (error: any) {
        console.error('[AI Analysis] Internal Server Error:', error);
        return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
    }
}
